Repository cloudflare/isbgpsafeyet.com, pull requests merged in 2023-02, with the labels that each got.

#643 chore: Add RKOM ISP
  data/operators.csv
Labels: verified: filtering, verified: signed

#638 Add Netinternet Bilisim Teknolojileri (AS-NETINTERNET)(AS51559)
  data/operators.csv
Labels: verified: filtering, verified: signed

#633 add: advanced Wireless Network (AS133481) :tea:
  data/operators.csv
  data/twitter.csv
Labels: verified: signed, verified: not filtering

#631 Add AS25560
  data/operators.csv
  data/twitter.csv
Labels: verified: signed, verified: not filtering

#632 Add AS15456
  data/operators.csv
  data/twitter.csv
Labels: verified: signed, verified: not filtering

#629 Update operators.csv
  data/operators.csv
Labels: verified: filtering, verified: signed

#625 Adding WARI.NET COMUNICACIONES S.R.L
  data/operators.csv
Labels: verified: not filtering

#621 chore: update signing/safety status of Trustpower ISP to safe
  data/operators.csv
Labels: verified: filtering, verified: signed

#620 Update operators.csv
  data/operators.csv
Labels: verified: filtering, verified: signed

#584 Add ACT ISP (AS24309)
  data/operators.csv
Labels: verified: filtering, verified: signed

#602 Update operators.csv
  data/operators.csv
Labels: verified: filtering, verified: signed

#579 Update operators.csv
  data/operators.csv
Labels: verified: filtering, verified: signed

#568 Update operators.csv
  data/operators.csv
Labels: verified: filtering, verified: signed
