Repository cloudflare/isbgpsafeyet.com, pull requests merged in 2024-09, with the labels that each got.

#759 Add AS25291 as safe transit provider
  data/operators.csv
Labels: verified: filtering, verified: signed

#760 Add AS5405 to list of safe operators
  data/operators.csv
Labels: verified: signed

#685 Init7 is now safe
  data/operators.csv
Labels: verified: filtering, verified: partially signed

#640 Update operators.csv
  data/operators.csv
Labels: verified: filtering, verified: signed
