Repository cloudflare/isbgpsafeyet.com, pull requests merged in 2024-08, with the labels that each got.

#754 Add AS8560 - IONOS SE
  data/operators.csv
Labels: verified: filtering, verified: signed

#755 Update AS1239 - T-Mobile
  data/operators.csv
Labels: verified: filtering, verified: partially signed

#756 Update operators.csv
  data/operators.csv
Labels: verified: signed, verified: not filtering
