Repository cloudflare/isbgpsafeyet.com, pull requests merged in 2024-07, with the labels that each got.

#732 Update operators.csv
  data/operators.csv
Labels: status: pending response, verified: signed

#734 Update operators.csv
  data/operators.csv
Labels: status: pending response

#752 Added Swiss ISP Wifx to operators.csv
  data/operators.csv
Labels: status: pending response, verified: signed, verified: not filtering
